// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: search.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchService_IndexGig_FullMethodName       = "/search.SearchService/IndexGig"
	SearchService_UpdateIndexGig_FullMethodName = "/search.SearchService/UpdateIndexGig"
	SearchService_DeleteGig_FullMethodName      = "/search.SearchService/DeleteGig"
	SearchService_SearchGig_FullMethodName      = "/search.SearchService/SearchGig"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	IndexGig(ctx context.Context, in *IndexGigRequest, opts ...grpc.CallOption) (*SearchEmptyRes, error)
	UpdateIndexGig(ctx context.Context, in *IndexGigRequest, opts ...grpc.CallOption) (*SearchEmptyRes, error)
	DeleteGig(ctx context.Context, in *DeleteDocumentReq, opts ...grpc.CallOption) (*SearchEmptyRes, error)
	SearchGig(ctx context.Context, in *SearchGigReq, opts ...grpc.CallOption) (*SearchGigRes, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) IndexGig(ctx context.Context, in *IndexGigRequest, opts ...grpc.CallOption) (*SearchEmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEmptyRes)
	err := c.cc.Invoke(ctx, SearchService_IndexGig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) UpdateIndexGig(ctx context.Context, in *IndexGigRequest, opts ...grpc.CallOption) (*SearchEmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEmptyRes)
	err := c.cc.Invoke(ctx, SearchService_UpdateIndexGig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) DeleteGig(ctx context.Context, in *DeleteDocumentReq, opts ...grpc.CallOption) (*SearchEmptyRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEmptyRes)
	err := c.cc.Invoke(ctx, SearchService_DeleteGig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchGig(ctx context.Context, in *SearchGigReq, opts ...grpc.CallOption) (*SearchGigRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGigRes)
	err := c.cc.Invoke(ctx, SearchService_SearchGig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility.
type SearchServiceServer interface {
	IndexGig(context.Context, *IndexGigRequest) (*SearchEmptyRes, error)
	UpdateIndexGig(context.Context, *IndexGigRequest) (*SearchEmptyRes, error)
	DeleteGig(context.Context, *DeleteDocumentReq) (*SearchEmptyRes, error)
	SearchGig(context.Context, *SearchGigReq) (*SearchGigRes, error)
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchServiceServer struct{}

func (UnimplementedSearchServiceServer) IndexGig(context.Context, *IndexGigRequest) (*SearchEmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IndexGig not implemented")
}
func (UnimplementedSearchServiceServer) UpdateIndexGig(context.Context, *IndexGigRequest) (*SearchEmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIndexGig not implemented")
}
func (UnimplementedSearchServiceServer) DeleteGig(context.Context, *DeleteDocumentReq) (*SearchEmptyRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGig not implemented")
}
func (UnimplementedSearchServiceServer) SearchGig(context.Context, *SearchGigReq) (*SearchGigRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchGig not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}
func (UnimplementedSearchServiceServer) testEmbeddedByValue()                       {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	// If the following call pancis, it indicates UnimplementedSearchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_IndexGig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexGigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).IndexGig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_IndexGig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).IndexGig(ctx, req.(*IndexGigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_UpdateIndexGig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IndexGigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).UpdateIndexGig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_UpdateIndexGig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).UpdateIndexGig(ctx, req.(*IndexGigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_DeleteGig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).DeleteGig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_DeleteGig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).DeleteGig(ctx, req.(*DeleteDocumentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchGig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchGig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchGig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchGig(ctx, req.(*SearchGigReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndexGig",
			Handler:    _SearchService_IndexGig_Handler,
		},
		{
			MethodName: "UpdateIndexGig",
			Handler:    _SearchService_UpdateIndexGig_Handler,
		},
		{
			MethodName: "DeleteGig",
			Handler:    _SearchService_DeleteGig_Handler,
		},
		{
			MethodName: "SearchGig",
			Handler:    _SearchService_SearchGig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search.proto",
}
